### ISSUE TITLE
Massive lag in parts of Nether.  Entity count skyrockets.

### ISSUE THREAD

**Issue by JHallman** [Beyond-Reality/BeyondRealityModPack#202]
I've just recently reached the Nether in my singleplayer Beyond Reality world (2.2.4 Beta) and I've been stonewalled by massive lag (0-1 fps).
In my initial world, it hit me as soon as I zoned into the nether.  The portal was inside of a fortress this time.

I tried I again on a few test worlds with different Nether spawns.  Some of these started lagging immediately, whereas in others I could fly around for a while before the lag began.  Once it starts it doesn't seem to stop until I leave the nether, though it does prove impossible to leave the area without dying at <1 fps.  I did notice that it seemed to occur near nether fortresses; I couldn't tell every time though.

When I brought up the debug screen, it showed 3k plus entities and climbing (it would reach 20k after a minute or so).  In the worlds where I was able to fly the count stayed around 100 until certain areas where it began to climb rapidly and tanked the game.

I had already removed Primitive mobs, and the related script before I even started the map as it apparently had a memory leak of some sort (or just unchecked spawning).

My first thought was that Biomes o Plenty was the culprit due to the localized nature of the lag.  Disabling its Nether Biomes had no effect though, even on a fresh world/nether.

I can provide any logs that may be needed, but I've looked through most of them and haven't been able to find anything relevant to the issue, no spammed logs or such.

**Comment by JHallman** [comment]
I have also found and read over a similar issue raised earlier today.  The user closed the issue stating that Aroma Backup was the culprit.

I have not had Any Aroma mods installed at any point during my time playing BR.

**Comment by shobu9** [comment]
It should clear after exploring the chunks it happened to the public server too...

**Comment by og1996** [comment]
I was the reporter of #196. It stopped happening for a while immediately after removing aromabackup, but then reappeared. Its definitely tied to the spawners in the doom-like dungeons areas. If I fly away from them, the lag disappears. I can even go near the blaze spawners in fortresses without issue. 

One workaround I found is to reduce chunk view distance to minimum while in the nether. It doesn't prevent the entities from going up, but they do so at a significantly reduced rate in SSP. This gives me about 5 minutes before I have to relog into Minecraft. I doubt this works for SMP.

**Comment by spinner2727** [comment]
The culprit seems to be the new version of Ender IO, as mentioned here https://github.com/CrazyPants/EnderIO/issues/2027.  Downgrading to the Ender IO version in 2.2.3C of the pack fixes the lag issues (for now, until the fix is released), which were most noticeable in the Doom Like Dungeons.

**Comment by Buuz135** [comment]
Fixed in 2.2.5

**Comment by quikstrike** [comment]
So my server just ran into this same problem on 2.2.5, so it looks like it is still an issue.

**Comment by NayNayYakazami** [comment]
I am a player on Quikstrike's server, the issue we have been running into after the update - before we rolled back to the previous version - was that the nether was spawning Wither Skeletons by the thousand - even with no chunks loaded or players present.

Secondarily, when I would go into the nether, entity count would start skyrocketing by a thousand every few seconds to the point FPS dropped to 0-1.

**Comment by StevenSpinn** [comment]
2.2.5 is still using EnderIO 2.2.8.349, which was the version I was having the issue with on in my previous post.  It should be updated to 2.2.8.367, where this issue is fixed.

**Comment by spinner2727** [comment]
2.2.5 is still using EnderIO 2.2.8.349, which was the version I was having the issue with on in my previous post. It should be updated to 2.2.8.367, where this issue is fixed.

**Comment by Buuz135** [comment]
Really fixed in 2.2.6
