### ISSUE TITLE
Silver Ore not maceratable

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#204]
Got yet another bug for you. Sorry. The only way to deal with silver ore is to put it into a pulverizer or forge hammer. If this is by design, then keep it, but if not, it should be changed. I have to put it straight into a furnace to do anything with it. Once you get a pulverizer, you can turn it into crushed ore and have it go down the processing train. Again, do not change this if it was done on purpose.

**Comment by shobu9** [comment]
@Dominance An other Minetweaker Script to add #162

**Comment by Buuz135** [comment]
Fixed in 2.2.5

**Comment by TheRailfan** [comment]
I would close this, but 2.2.5 has not been released yet, so it is still an issue. When 2.2.5 is released and it has been verified this is fixed, the issue will be closed.

**Comment by Dyonovan** [comment]
Closing issue as it will be fixed in 2.2.5. If it isnt, please reopen

**Comment by Dyonovan** [comment]
Are you using the IC2 Macerator or the gregtech one? if you are using the IC2 one this is intentional. You are supposed to use the GregTech One. This will not be changed

**Comment by shobu9** [comment]
#162 is still here sadly on Br server the grindstone doesn't work with some gregtech ores
should i make some minetweaking and then be commited?

**Comment by Tyriael-Soban** [comment]
This one would seem to of returned in 2.2.7
![2015-05-19_21 06 38](https://cloud.githubusercontent.com/assets/9297841/7718265/007e0d56-fe6b-11e4-99d8-6e82d6cd3da8.png)
not a good start to a new modpack.

**Comment by Dyonovan** [comment]
Silver Ore is NOT meant to be macerated in the Bronze Macerator. Works fine in the electric one. This is intentionally done by Greg as Silver is not a early game ore. Tested and Verified it works in Electric Macerator. 

Also, this is not a new modpack. We have been around since Minecraft 1.6

**Comment by Tyriael-Soban** [comment]
Is that supposed to apply to lead as well?
One more thing, i when i said "not a good start to a new modpack" i mean, not a good start to something i just started playing, thats a very obscure "intentional" change - though i suppose Infitech 2 did use spiceoflife at one point ...

**Comment by Dyonovan** [comment]
Ahh ok. Just a heads up, you can process silver in the Quartz GrindStone.

As to lead, same thing. Greg has very strict teirs of things. Basically early game is all about tin, copper, and iron.

**Comment by Tyriael-Soban** [comment]
Jason must of changed it for infitech then, i apologize for the confusion.

**Comment by Dyonovan** [comment]
I am guessing this is your first voyage into Hardcore GregTech :) There are a LOT of changes that greg makes. We try to balance EVERYTHING in the pack against greg. You will really notice that most other mods have been changed to use Steel. Have fun and if you have any issues, I almost always in the #beyondreality irc.esper.net channel. Come by and say hi!

**Comment by TheRailfan** [comment]
I think that should be on the wiki somewhere, especially the official gregtech one. It is definitely my first go at it, so things like that have thrown me off. That's why I have a test world to make sure everything works properly. One thing I don't like is if something is uncraftable it should not show up in NEI, but that's another problem I ran into once with railcraft fireboxes. So far, it's been just what I have been looking for in a mod pack. A long hard journey to the end, and when you do get there, it's not any easier, and I like a good challenge

**Comment by Dyonovan** [comment]
The gregtech wiki has never been great. That always been an issue with the mod.

I like the idea of hiding things from nei if not craftable, but that is a ton of work and there are also times that single player/server ops need access to that stuff. I will talk to the team about this but no promises.

**Comment by TheRailfan** [comment]
If you can't do it, there is nothing wrong with that. I know now that if its not craftable that's probably for a reason. And gregtech is known for doing strange things that you think are bugs but really aren't. Either way, I appreciate the effort
